"""Writing one corrected C-kernel: its segments and the comments about them.

``ckopn`` reserves the comment area and ``ckw03`` writes segments, but nothing
in the CK interface fills the comments; that is done through the plain DAF
interface afterwards, on the file the CK interface has already closed.  This
module runs the two halves in the one order that works, and reserves the room
the comments need before the file is opened.

Reserving matters.  A comment that does not fit what was reserved is still
stored -- SPICE extends the area by shifting every data record in the file --
so the failure is a rewritten file rather than a lost comment, and it is
invisible unless the file is measured before and after.  It is measurable: the
address of the first data record does not move when the reservation was enough
and does when it was not.

A write that fails part way through is closed with ``dafcls`` rather than
``ckcls``, and the half-written file is removed.  ``ckcls`` on a C-kernel that
received no segment raises in its own right and leaves the file open, so using
it on the failure path would replace the error worth reading with one that is
not *and* leak the handle; ``dafcls`` closes the file and has nothing to say
about segments.

That covers the segments, and it is why everything else is judged before the
file is opened.  The comment area is the case that makes the ordering matter:
it is written after ``ckcls`` has already succeeded, so a line SPICE cannot
store, refused there, would leave behind a kernel that furnishes cleanly and
covers exactly the right exposures with an empty comment area -- a file
indistinguishable from a good product except for the provenance record the
comment area exists to carry, and one the guard against overwriting an existing
kernel then stops the operator from simply regenerating.
"""

from collections.abc import Sequence
from pathlib import Path

import cspyce

from spindoctor.cli.ck.comments import (
    check_comment_lines,
    reserved_comment_chars,
    write_comment_area,
)
from spindoctor.cli.ck.segment import CkSegment, write_segment

# The longest internal file name SPICE stores in a DAF file record.
_IFNAME_MAX_CHARS = 60


def write_ck_file(path: Path, segments: Sequence[CkSegment], comment_lines: Sequence[str]) -> None:
    """Write one corrected C-kernel, comments and all.

    Parameters:
        path: The file to create.  It must not exist: SPICE refuses to open an
            existing file for creation, and a corrected kernel is regenerated
            by replacing it rather than by appending to it.
        segments: The segments to write, in order.  At least one is required.
        comment_lines: The comment area to attach.  At least one line is
            required.

    Raises:
        ValueError: if no segment is given -- SPICE refuses to close a
            C-kernel holding none, and the half-written file would be left
            behind -- if no comment line is given, if a comment line is one
            SPICE cannot store and read back unchanged, if the file's own name
            is too long to be its internal name, or if a file of that name
            already exists.  Every one of those is judged before the file is
            opened.  Also if SPICE refuses a segment once the file is open,
            which it does for a segment identifier holding a non-printing
            character or a quaternion of magnitude zero.
        RuntimeError: if SPICE cannot create the file, for example because the
            directory does not exist or cannot be written to.
        OSError: if SPICE refuses a segment write for an operating-system
            reason once the file is open.

    Whatever the failure, no file is left behind: the up-front refusals happen
    before ``ckopn``, and a failure after it closes the file and removes it.
    """
    if len(segments) == 0:
        raise ValueError(
            f'no segments to write to {path.name}; a corrected kernel carrying none claims a '
            f'correction it does not hold, and SPICE refuses to close it'
        )
    if len(comment_lines) == 0:
        raise ValueError(f'no comment lines to write to {path.name}')
    # Before ``ckopn``, because the comment area is written after ``ckcls``:
    # a line SPICE cannot store, judged there, would leave behind a complete
    # and furnishable kernel whose comment area is empty -- and the guard on an
    # existing file below would then block the obvious next step of fixing the
    # line and running again.
    check_comment_lines(comment_lines)
    if path.exists():
        # Said here rather than left to SPICE, which reports an operating
        # system status number and no reason at all.  A corrected kernel is
        # regenerated by replacing it, so the operator has to say which of the
        # two files they meant to keep.
        raise ValueError(
            f'{path} already exists; a corrected kernel is regenerated by replacing it, so remove '
            f'or move the existing file rather than writing beside it'
        )
    internal_name = _internal_name(path)
    handle = int(cspyce.ckopn(str(path), internal_name, reserved_comment_chars(comment_lines)))
    try:
        for segment in segments:
            write_segment(handle, segment)
    except Exception:
        # Closed through the plain DAF interface rather than ``ckcls``, and
        # measured rather than assumed: ``ckcls`` on a C-kernel that received
        # no segment raises SPICE(NOSEGMENTSFOUND) *and leaves the file open*,
        # so using it here would both replace the failure worth reading with
        # one that is not and leak the handle anyway.  ``dafcls`` closes it and
        # has nothing to say about segments.
        cspyce.dafcls(handle)
        # The file ``ckopn`` created is removed with it.  It holds no usable
        # segment, and leaving it behind would make the obvious next step --
        # fix the cause and run again -- fail on the refusal to write over an
        # existing corrected kernel.
        path.unlink(missing_ok=True)
        raise
    cspyce.ckcls(handle)
    write_comment_area(path, comment_lines)


def _internal_name(path: Path) -> str:
    """Return the internal file name a corrected kernel records.

    Parameters:
        path: The file being written.

    Returns:
        The file's basename, which is what identifies it once it has been
        copied somewhere else.

    Raises:
        ValueError: if the basename does not fit the field SPICE stores it in,
            since a truncated internal name would identify a different file.
    """
    name = path.name
    if len(name) > _IFNAME_MAX_CHARS:
        raise ValueError(
            f'{name!r} is longer than the {_IFNAME_MAX_CHARS} characters SPICE stores as a '
            f"file's internal name"
        )
    return name


def first_data_record(path: Path) -> int:
    """Return the record number of a DAF file's first data record.

    This is what the comment area's reservation buys: the comments sit between
    the file record and the data, so a file whose reservation was large enough
    has the same first data record before and after its comments are added, and
    a file whose reservation was too small does not -- SPICE moved the data.

    Parameters:
        path: The file to measure.

    Returns:
        The record number of the first descriptor record.

    Raises:
        OSError: if the file cannot be opened for reading.
    """
    handle = int(cspyce.dafopr(str(path)))
    try:
        _nd, _ni, _ifname, fward, _bward, _free = cspyce.dafrfr(handle)
        return int(fward)
    finally:
        cspyce.dafcls(handle)
